<project xmlns="http://maven.apache.org/POM/4.0.0">
  <modelVersion>4.0.0</modelVersion>
  <parent><groupId>dev.graphine.analyzer</groupId><artifactId>analyzer-jdt-parent</artifactId><version>0.1.0</version><relativePath>../pom.xml</relativePath></parent>
  <artifactId>project-resolver</artifactId>
  <dependencies>
    <dependency><groupId>dev.graphine.analyzer</groupId><artifactId>analyzer-protocol</artifactId><version>${project.version}</version></dependency>
    <dependency><groupId>org.junit.jupiter</groupId><artifactId>junit-jupiter</artifactId><scope>test</scope></dependency>
  </dependencies>
</project>
