[package]
name = "app"
version = "0.1.0"
edition = "2024"
build = "build.rs"

[features]
default = []
fancy = []

[dependencies]
local-macro = { path = "../local-macro" }
support = { path = "../support" }

[[example]]
name = "demo"
path = "examples/demo.rs"

[[bench]]
name = "throughput"
path = "benches/throughput.rs"
harness = false
