[package]
name = "graphine-rust-analyzer"
version = "0.1.0"
edition.workspace = true
license.workspace = true
rust-version.workspace = true

[[bin]]
name = "graphine-rust-analyzer"
path = "src/main.rs"

[dependencies]
anyhow.workspace = true
camino = "1.2"
cargo_metadata = "=0.23.1"
graphine-protocol = { path = "../graphine-protocol" }
serde_json.workspace = true
sha2 = "0.10"
toml = "0.9"
walkdir = "2.5"
ra_ap_hir = "=0.0.342"
ra_ap_cfg = "=0.0.342"
ra_ap_ide_db = "=0.0.342"
ra_ap_load-cargo = "=0.0.342"
ra_ap_proc_macro_api = "=0.0.342"
ra_ap_project_model = "=0.0.342"
ra_ap_syntax = "=0.0.342"
ra_ap_vfs = "=0.0.342"

[lints]
workspace = true
